name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - '*'

variables:
- group: pypi-credentials

pool:
  vmImage: 'ubuntu-latest'


stages:

- stage: unitTests
  displayName: Run Unit Tests
  jobs:
  - job: unitTests
    displayName: Run Unit Tests

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.9'
        displayName: 'Use Python 3.9'

      - script: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install poetry==1.1.11
        displayName: 'Install poetry 1.1.11'
      
      - script: python -m poetry install
        displayName: 'Install dependencies'
        
      - script: python -m poetry run python -m pytest
        displayName: 'Test with pytest'

- stage: build
  displayName: Build package and post to PyPI
  dependsOn: unitTests
  # Run only if previous stage succeeded. Don't run for tagging events
  condition: and(succeeded(), eq(variables.isMaster, true))

  jobs:
    - job: buildAndUpload
      displayName: Build and Upload to PyPI

      steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.9'
        displayName: 'Use Python 3.9'

      - script: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install poetry==1.1.11
        displayName: 'Install poetry 1.1.11'
      
      - script: python -m poetry install
        displayName: 'Install dependencies'
      
      - script: python -m poetry publish --build --username $(PYPI_USER) --password $(PYPI_TOKEN)
        
