on:
  push:
    branches: [ master ]

jobs:
  test and publish:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
      
    - name: Install poetry 1.1.11
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install poetry==1.1.11
    
    - name: Install dependencies
      run: python -m poetry install

    - name: Test with pytest
      run: python -m poetry run python -m pytest
     
    - name: Build and publish
      run: python -m poetry publish --build --username ${{ secrets.PYPI_USER }} --password ${{ secrets.PYPI_API_TOKEN }}

    # implement version bumping with poetry and commit bump to master
          
